name: firebase_eco
description: "Ecommerce Project App"


publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.3.0 <4.0.0'



# ---------------------- PACKAGES ---------------------- #
dependencies:

  # Version
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.0.0

  # Utilities Package
  intl: ^0.19.0

  # Url Launcher
  url_launcher: ^6.2.6

  # logger
  logger: ^2.3.0

  # HTTP
  http: ^1.2.1

  # Connectivity Plus
  connectivity_plus: ^6.0.3

  # Firebase Core
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1



  # Native Splash:
  flutter_native_splash: ^2.4.0

  # Product Specifics
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

# ---------------------- PACKAGES END ---------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # ---------------------- LOCAL ASSETS ---------------------- #
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  # ---------------------- LOCAL FONTS ---------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
