name: firebase_eco
description: "Ecommerce Project App"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0
  intl: ^0.19.0
  url_launcher: ^6.2.6
  logger: ^2.3.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/logos/
  - assets/icons/brands/
  - assets/images/content/
  - assets/images/banners/
  - assets/images/reviews/
  - assets/images/products/
  - assets/icons/categories/
  - assets/images/animations/
  - assets/icons/payment_methods/
  - assets/images/on_boarding_images/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
