// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDngaC-oaoHOQK_0hjRrn3UggD4YleQKcI',
    appId: '1:348212590592:web:7d96b0d4876b93604a00e5',
    messagingSenderId: '348212590592',
    projectId: 'feco-eaut',
    authDomain: 'feco-eaut.firebaseapp.com',
    databaseURL: 'https://feco-eaut-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feco-eaut.appspot.com',
    measurementId: 'G-MDZGX2GMEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClb1Uk9nR41QCBPjMlj4W5Qe8nfhtzeko',
    appId: '1:348212590592:android:15bc8486e96d4a304a00e5',
    messagingSenderId: '348212590592',
    projectId: 'feco-eaut',
    databaseURL: 'https://feco-eaut-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feco-eaut.appspot.com',
  );

}